# Generated by Django 5.1.4 on 2025-01-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='aadhar_or_kyc',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
